<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <title>ملصق باركود</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, sans-serif;
            width: 576px;
            margin: 0;
            padding: 20px 24px;
            color: #000;
            background: #fff;
            text-align: center;
        }
        .name { font-size: 28px; font-weight: bold; margin-bottom: 4px; }
        .price { font-size: 26px; margin-bottom: 12px; }
        svg { max-width: 100%; }
    </style>
</head>
<body>
    <div class="name">{{ $product->name }}</div>
    <div class="price">{{ number_format($product->sale_price, 2) }}</div>
    <svg id="barcode"></svg>

    <script src="{{ asset('vendor/jsbarcode/JsBarcode.all.min.js') }}"></script>
    <script>
        // EAN13 requires exactly 13 digits with a valid check digit and JsBarcode
        // silently renders nothing if that fails; CODE128 accepts any value, so
        // it's the safe fallback for barcodes that were typed in by hand rather
        // than generated by the "توليد باركود" button.
        const barcodeValue = "{{ $product->barcode }}";
        const isValidEan13 = /^\d{13}$/.test(barcodeValue);

        JsBarcode("#barcode", barcodeValue, {
            format: isValidEan13 ? "EAN13" : "CODE128",
            width: 3,
            height: 100,
            fontSize: 26,
            margin: 0,
            valid: function (valid) {
                if (!valid) {
                    JsBarcode("#barcode", barcodeValue, {
                        format: "CODE128",
                        width: 3,
                        height: 100,
                        fontSize: 26,
                        margin: 0,
                    });
                }
            },
        });
    </script>
</body>
</html>
